# Generated by Django 3.0.4 on 2020-03-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField(verbose_name='Problem Statement')),
                ('approach', models.TextField(verbose_name='Approach')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Website')),
                ('link', models.URLField(max_length=5000, verbose_name='URL')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code.Problem')),
            ],
        ),
    ]
