# Generated by Django 3.0.4 on 2020-03-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Languages',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='SolutionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code.LanguageCategory')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code.Problem')),
            ],
            options={
                'verbose_name': 'Solutions',
                'verbose_name_plural': 'Solutions',
            },
        ),
    ]
