# Generated by Django 3.0.4 on 2020-03-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0002_languagecategory_solutioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_note',
            field=models.CharField(default='hello', max_length=50, verbose_name='Short Nate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='tip',
            field=models.TextField(default='hello', verbose_name='Tips and Tricks'),
            preserve_default=False,
        ),
    ]
