# Generated by Django 3.0.4 on 2020-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0006_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioncode',
            name='file',
            field=models.FileField(blank=True, upload_to='CodeS/'),
        ),
    ]
