# Generated by Django 3.0.4 on 2020-04-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0007_solutioncode_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutioncode',
            name='file',
        ),
    ]
