# Generated by Django 3.0.4 on 2020-04-01 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0009_commentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
