# Generated by Django 3.0.4 on 2020-04-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0010_commentdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Dates',
                'verbose_name_plural': 'Dates',
            },
        ),
    ]
