# Generated by Django 3.0.4 on 2020-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0012_resourcetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='Code.ResourceTag'),
        ),
    ]
