# Generated by Django 3.0.4 on 2020-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0016_todo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ToDo Level',
                'verbose_name_plural': 'ToDo Level',
            },
        ),
    ]
