# Generated by Django 3.0.4 on 2020-04-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0017_todolevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Code.ToDoLevel'),
            preserve_default=False,
        ),
    ]
